
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec  9 2024 22:01:57 WET (Dec  9 2024 22:01:57 UTC)

// Verification Directory fv/BATCHARGERctr 

module BATCHARGERctr(cc, tc, cv, imonen, vmonen, tmonen, vtok, vbat,
     ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend, clk,
     en, rstz, dvdd, dgnd);
  input vtok, clk, en, rstz;
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  output cc, tc, cv, imonen, vmonen, tmonen;
  inout dvdd, dgnd;
  wire vtok, clk, en, rstz;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire cc, tc, cv, imonen, vmonen, tmonen;
  wire dvdd, dgnd;
  wire [2:0] nxt_state;
  wire [7:0] charge_time;
  wire [7:0] counter;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, logic_0_1_net, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_115, n_116, n_117;
  wire n_119, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229;
  assign imonen = cv;
  QDFFEHD \nxt_state_reg[1] (.CK (clk), .D (n_229), .Q (nxt_state[1]));
  AO2222CHD g1768__2398(.A1 (n_228), .A2 (n_215), .B1 (n_214), .B2
       (n_205), .C1 (n_227), .C2 (n_207), .D1 (nxt_state[1]), .D2
       (n_225), .O (n_229));
  QDFFEHD \nxt_state_reg[2] (.CK (clk), .D (n_224), .Q (nxt_state[2]));
  QDFFEHD \nxt_state_reg[0] (.CK (clk), .D (n_226), .Q (nxt_state[0]));
  NR2BHD g1796__5107(.I1 (n_227), .I2 (n_223), .O (n_228));
  AO12EHD g1761__6260(.A1 (n_219), .B1 (nxt_state[0]), .B2 (n_225), .O
       (n_226));
  AO12EHD g1762__4319(.A1 (n_222), .B1 (nxt_state[2]), .B2 (n_225), .O
       (n_224));
  OAI112BHD g1807__8428(.A1 (n_221), .B1 (n_218), .C1 (n_117), .C2
       (logic_0_1_net), .O (n_223));
  OAI13BHD g1788__5526(.A1 (n_221), .B1 (n_191), .B2 (n_220), .B3
       (n_212), .O (n_222));
  AO13EHD g1787__6783(.A1 (n_227), .B1 (n_208), .B2 (n_213), .B3
       (n_218), .O (n_219));
  NR2CHD g1804__3680(.I1 (n_216), .I2 (n_217), .O (n_227));
  OR2B1CHD g1815__1617(.I1 (n_217), .B1 (n_216), .O (n_221));
  NR2CHD g1797__2802(.I1 (n_214), .I2 (n_225), .O (n_215));
  ND3CHD g1831__1705(.I1 (n_211), .I2 (n_213), .I3 (n_218), .O (n_217));
  NR2CHD g1805__5122(.I1 (n_212), .I2 (n_213), .O (n_225));
  NR3BHD g1808__8246(.I1 (n_212), .I2 (n_220), .I3 (n_136), .O (n_214));
  INVDHD g1836(.I (n_220), .O (n_213));
  OAI13BHD g1841__7098(.A1 (en), .B1 (n_137), .B2 (n_211), .B3 (n_210),
       .O (n_220));
  INVCKDHD g1847(.I (n_212), .O (n_218));
  ND2CHD g1854__6131(.I1 (n_209), .I2 (n_169), .O (n_210));
  QDFFEHD \charge_time_reg[3] (.CK (clk), .D (n_196), .Q
       (charge_time[3]));
  QDFFEHD \charge_time_reg[5] (.CK (clk), .D (n_195), .Q
       (charge_time[5]));
  OR3B2CHD g1852__1881(.I1 (n_204), .B1 (vtok), .B2 (rstz), .O (n_212));
  QDFFEHD \charge_time_reg[1] (.CK (clk), .D (n_200), .Q
       (charge_time[1]));
  QDFFEHD \charge_time_reg[6] (.CK (clk), .D (n_206), .Q
       (charge_time[6]));
  QDFFEHD \charge_time_reg[7] (.CK (clk), .D (n_203), .Q
       (charge_time[7]));
  QDFFEHD \charge_time_reg[0] (.CK (clk), .D (n_197), .Q
       (charge_time[0]));
  QDFFEHD \charge_time_reg[4] (.CK (clk), .D (n_199), .Q
       (charge_time[4]));
  QDFFEHD \charge_time_reg[2] (.CK (clk), .D (n_198), .Q
       (charge_time[2]));
  AOI22BHD g1859__5115(.A1 (n_208), .A2 (n_207), .B1 (n_90), .B2
       (n_194), .O (n_209));
  OAI22CHD g1769__7482(.A1 (n_202), .A2 (n_165), .B1 (n_164), .B2
       (n_201), .O (n_206));
  AOI112BHD g1801__4733(.A1 (n_187), .B1 (n_154), .C1 (n_170), .C2
       (n_130), .O (n_205));
  OAI22CHD g1855__6161(.A1 (n_159), .A2 (n_186), .B1 (n_193), .B2
       (n_161), .O (n_204));
  OAI22CHD g1773__9315(.A1 (n_202), .A2 (n_180), .B1 (n_179), .B2
       (n_201), .O (n_203));
  OAI22CHD g1772__9945(.A1 (n_202), .A2 (n_45), .B1 (n_55), .B2
       (n_201), .O (n_200));
  OAI22CHD g1776__2883(.A1 (n_202), .A2 (n_139), .B1 (n_147), .B2
       (n_201), .O (n_199));
  OAI22CHD g1775__2346(.A1 (n_202), .A2 (n_61), .B1 (n_57), .B2
       (n_201), .O (n_198));
  OAI22CHD g1774__1666(.A1 (n_202), .A2 (charge_time[0]), .B1 (n_54),
       .B2 (n_201), .O (n_197));
  OAI22CHD g1777__7410(.A1 (n_202), .A2 (n_135), .B1 (n_162), .B2
       (n_201), .O (n_196));
  OAI22CHD g1778__6417(.A1 (n_202), .A2 (n_167), .B1 (n_166), .B2
       (n_201), .O (n_195));
  QDFFEHD \counter_reg[6] (.CK (clk), .D (n_192), .Q (counter[6]));
  QDFFEHD \counter_reg[5] (.CK (clk), .D (n_190), .Q (counter[5]));
  QDFFEHD \counter_reg[7] (.CK (clk), .D (n_188), .Q (counter[7]));
  AO2222BHD g1868__5477(.A1 (n_172), .A2 (n_142), .B1 (n_59), .B2
       (n_38), .C1 (n_28), .C2 (vbat[7]), .D1 (n_141), .D2 (n_127), .O
       (n_194));
  AO2222BHD g1876__2398(.A1 (n_176), .A2 (n_146), .B1 (n_58), .B2
       (n_35), .C1 (n_29), .C2 (vbat[7]), .D1 (n_145), .D2 (n_128), .O
       (n_207));
  AN4B1BHD g1860__5107(.I1 (n_173), .I2 (n_110), .I3 (n_23), .B1
       (n_160), .O (n_193));
  OAI13BHD g1767__6260(.A1 (n_94), .B1 (n_182), .B2 (n_191), .B3
       (n_189), .O (n_192));
  OAI13BHD g1766__4319(.A1 (n_93), .B1 (n_178), .B2 (n_191), .B3
       (n_189), .O (n_190));
  QDFFEHD \counter_reg[4] (.CK (clk), .D (n_185), .Q (counter[4]));
  OAI13BHD g1760__8428(.A1 (n_95), .B1 (n_175), .B2 (n_191), .B3
       (n_189), .O (n_188));
  AO2222CHD g1806__5526(.A1 (n_163), .A2 (n_148), .B1 (n_31), .B2
       (n_41), .C1 (charge_time[7]), .C2 (n_7), .D1 (n_78), .D2
       (n_109), .O (n_187));
  AN4B1BHD g1863__6783(.I1 (n_183), .I2 (n_112), .I3 (n_22), .B1
       (n_158), .O (n_186));
  ND3CHD g1791__3680(.I1 (n_201), .I2 (n_184), .I3 (rstz), .O (n_202));
  QDFFEHD \counter_reg[3] (.CK (clk), .D (n_168), .Q (counter[3]));
  OAI13BHD g1771__1617(.A1 (n_96), .B1 (n_156), .B2 (n_191), .B3
       (n_189), .O (n_185));
  OAI112BHD g1798__2802(.A1 (n_184), .B1 (rstz), .C1 (n_157), .C2
       (n_119), .O (n_201));
  OAI112BHD g1874__1705(.A1 (n_152), .B1 (n_107), .C1 (n_26), .C2
       (tbat[3]), .O (n_183));
  MAOI1CHD g1799__5122(.A1 (n_181), .A2 (counter[6]), .B1 (counter[6]),
       .B2 (n_181), .O (n_182));
  MUX2CHD g1792__8246(.S (n_151), .A (n_179), .B (charge_time[7]), .O
       (n_180));
  MAOI1CHD g1800__7098(.A1 (n_177), .A2 (counter[5]), .B1 (counter[5]),
       .B2 (n_177), .O (n_178));
  OAI112BHD g1897__6131(.A1 (n_143), .B1 (n_84), .C1 (n_171), .C2
       (vcutoff[3]), .O (n_176));
  MAOI1CHD g1802__1881(.A1 (n_174), .A2 (counter[7]), .B1 (counter[7]),
       .B2 (n_174), .O (n_175));
  OAI112BHD g1875__5115(.A1 (n_153), .B1 (n_87), .C1 (n_25), .C2
       (tempmin[3]), .O (n_173));
  OAI112BHD g1902__7482(.A1 (n_144), .B1 (n_68), .C1 (n_171), .C2
       (vpreset[3]), .O (n_172));
  OAI112BHD g1817__4733(.A1 (n_140), .B1 (n_104), .C1 (n_32), .C2
       (ibat[3]), .O (n_170));
  AOI22BHD g1858__6161(.A1 (state[2]), .A2 (n_134), .B1 (state[2]), .B2
       (state[0]), .O (n_169));
  OAI13BHD g1765__9315(.A1 (n_97), .B1 (n_125), .B2 (n_191), .B3
       (n_189), .O (n_168));
  QDFFEHD \counter_reg[2] (.CK (clk), .D (n_150), .Q (counter[2]));
  MXL2CHD g1793__9945(.S (n_123), .A (n_166), .B (charge_time[5]), .OB
       (n_167));
  MUX2CHD g1795__2883(.S (n_133), .A (n_164), .B (charge_time[6]), .O
       (n_165));
  OAI112BHD g1814__2346(.A1 (n_122), .B1 (n_116), .C1 (n_162), .C2
       (tmax[3]), .O (n_163));
  OAI112BHD g1864__1666(.A1 (n_88), .B1 (n_19), .C1 (n_111), .C2
       (n_160), .O (n_161));
  QDFFEHD \counter_reg[1] (.CK (clk), .D (n_131), .Q (counter[1]));
  QDFFEHD \counter_reg[0] (.CK (clk), .D (n_121), .Q (counter[0]));
  OAI112BHD g1865__7410(.A1 (n_49), .B1 (n_24), .C1 (n_113), .C2
       (n_158), .O (n_159));
  OR3B1EHD g1818__6417(.I1 (n_149), .I2 (n_155), .B1 (counter[7]), .O
       (n_157));
  MAOI1CHD g1936__5477(.A1 (n_155), .A2 (counter[4]), .B1 (counter[4]),
       .B2 (n_155), .O (n_156));
  OAI112BHD g1812__2398(.A1 (n_77), .B1 (n_20), .C1 (n_64), .C2
       (n_129), .O (n_154));
  OAI112BHD g1887__5107(.A1 (n_72), .B1 (n_86), .C1 (n_85), .C2
       (tbat[2]), .O (n_153));
  OAI112BHD g1888__6260(.A1 (n_81), .B1 (n_106), .C1 (n_105), .C2
       (tempmax[2]), .O (n_152));
  NR3BHD g1809__4319(.I1 (n_164), .I2 (n_132), .I3 (n_138), .O (n_151));
  OAI13BHD g1764__8428(.A1 (n_91), .B1 (n_80), .B2 (n_191), .B3
       (n_189), .O (n_150));
  OR2EHD g1811__5526(.I1 (n_149), .I2 (n_155), .O (n_174));
  OR2EHD g1810__6783(.I1 (n_43), .I2 (n_155), .O (n_181));
  AOI112BHD g1820__3680(.A1 (n_79), .B1 (n_108), .C1 (n_147), .C2
       (tmax[4]), .O (n_148));
  OA112CHD g1899__1617(.A1 (n_145), .B1 (n_70), .C1 (n_69), .C2
       (vbat[4]), .O (n_146));
  OAI112BHD g1909__2802(.A1 (n_76), .B1 (n_67), .C1 (n_66), .C2
       (vbat[2]), .O (n_144));
  OAI112BHD g1912__1705(.A1 (n_65), .B1 (n_83), .C1 (n_82), .C2
       (vbat[2]), .O (n_143));
  OA112CHD g1898__5122(.A1 (n_141), .B1 (n_74), .C1 (n_73), .C2
       (vbat[4]), .O (n_142));
  OAI112BHD g1827__8246(.A1 (n_98), .B1 (n_103), .C1 (n_102), .C2
       (iend[2]), .O (n_140));
  MUX2EHD g1940__7098(.S (n_138), .A (charge_time[4]), .B (n_147), .O
       (n_139));
  OR2B1CHD g1935__6131(.I1 (n_155), .B1 (counter[4]), .O (n_177));
  OAI12CHD g1856__1881(.A1 (n_136), .B1 (n_53), .B2 (n_191), .O
       (n_137));
  MXL2CHD g1794__5115(.S (n_46), .A (n_162), .B (charge_time[3]), .OB
       (n_135));
  INVCKDHD g1872(.I (n_216), .O (n_134));
  NR2BHD g1803__7482(.I1 (n_132), .I2 (n_138), .O (n_133));
  OAI13BHD g1770__4733(.A1 (n_101), .B1 (n_30), .B2 (n_191), .B3
       (n_189), .O (n_131));
  AOI112BHD g1819__6161(.A1 (n_129), .B1 (n_63), .C1 (n_62), .C2
       (ibat[4]), .O (n_130));
  OAI12CHD g1910__9315(.A1 (n_71), .B1 (n_126), .B2 (vcutoff[5]), .O
       (n_128));
  OAI12CHD g1911__9945(.A1 (n_75), .B1 (n_126), .B2 (vpreset[5]), .O
       (n_127));
  MAOI1CHD g1938__2883(.A1 (n_124), .A2 (counter[3]), .B1 (counter[3]),
       .B2 (n_124), .O (n_125));
  OR2EHD g1939__2346(.I1 (n_147), .I2 (n_138), .O (n_123));
  OAI112BHD g1830__1666(.A1 (n_115), .B1 (n_40), .C1 (n_56), .C2
       (n_36), .O (n_122));
  OAI13BHD g1763__7410(.A1 (n_100), .B1 (n_191), .B2 (counter[0]), .B3
       (n_189), .O (n_121));
  NR2BHD g1748__6417(.I1 (n_119), .I2 (n_89), .O (cc));
  OR2B1CHD g1747__5477(.I1 (n_117), .B1 (en), .O (tmonen));
  OR3B2CHD g1837__2398(.I1 (tmax[2]), .B1 (charge_time[2]), .B2
       (n_115), .O (n_116));
  AN2CHD g1749__5107(.I1 (n_208), .I2 (en), .O (tc));
  AOI22BHD g1886__6260(.A1 (n_17), .A2 (n_112), .B1 (n_27), .B2
       (tempmax[5]), .O (n_113));
  AOI22BHD g1884__4319(.A1 (n_16), .A2 (n_110), .B1 (n_6), .B2
       (tbat[5]), .O (n_111));
  OAI22CHD g1828__8428(.A1 (n_21), .A2 (n_108), .B1 (n_166), .B2
       (tmax[5]), .O (n_109));
  AOI12CHD g1877__5526(.A1 (n_37), .B1 (n_39), .B2 (n_126), .O (n_216));
  OR2B1CHD g1937__6783(.I1 (n_124), .B1 (counter[3]), .O (n_155));
  ND3CHD g1893__3680(.I1 (n_106), .I2 (n_105), .I3 (tempmax[2]), .O
       (n_107));
  ND3CHD g1838__1617(.I1 (n_103), .I2 (n_102), .I3 (iend[2]), .O
       (n_104));
  ND2DHD g1780__2802(.I1 (counter[1]), .I2 (n_99), .O (n_101));
  ND2DHD g1781__1705(.I1 (counter[0]), .I2 (n_99), .O (n_100));
  MAO222CHD g1840__5122(.A1 (n_18), .B1 (n_0), .C1 (iend[1]), .O
       (n_98));
  ND2DHD g1782__8246(.I1 (counter[3]), .I2 (n_99), .O (n_97));
  ND2DHD g1783__7098(.I1 (counter[4]), .I2 (n_99), .O (n_96));
  ND2DHD g1784__6131(.I1 (counter[7]), .I2 (n_99), .O (n_95));
  ND2DHD g1785__1881(.I1 (counter[6]), .I2 (n_99), .O (n_94));
  ND2DHD g1786__5115(.I1 (counter[5]), .I2 (n_99), .O (n_93));
  OR3B2CHD g1746__7482(.I1 (n_51), .B1 (n_52), .B2 (en), .O (vmonen));
  ND2DHD g1779__4733(.I1 (counter[2]), .I2 (n_99), .O (n_91));
  INVDHD g1866(.I (n_89), .O (n_90));
  OR3B2CHD g1879__6161(.I1 (tempmin[6]), .B1 (n_42), .B2 (tbat[6]), .O
       (n_88));
  ND3CHD g1890__9315(.I1 (n_86), .I2 (n_85), .I3 (tbat[2]), .O (n_87));
  ND2DHD g1862__9945(.I1 (n_33), .I2 (state[2]), .O (n_136));
  ND3CHD g1924__2883(.I1 (n_83), .I2 (n_82), .I3 (vbat[2]), .O (n_84));
  MAO222CHD g1896__2346(.A1 (n_14), .B1 (n_8), .C1 (tempmax[1]), .O
       (n_81));
  XNR2CHD g1944__1666(.I1 (counter[2]), .I2 (n_50), .O (n_80));
  INVDHD g1821(.I (n_78), .O (n_79));
  OR3B2CHD g1823__7410(.I1 (ibat[6]), .B1 (n_44), .B2 (iend[6]), .O
       (n_77));
  MAO222CHD g1922__6417(.A1 (n_10), .B1 (n_1), .C1 (vbat[1]), .O
       (n_76));
  ND3CHD g1923__5477(.I1 (n_74), .I2 (n_73), .I3 (vbat[4]), .O (n_75));
  MAO222CHD g1901__2398(.A1 (n_15), .B1 (n_5), .C1 (tbat[1]), .O
       (n_72));
  ND3CHD g1925__5107(.I1 (n_70), .I2 (n_69), .I3 (vbat[4]), .O (n_71));
  ND3CHD g1926__6260(.I1 (n_67), .I2 (n_66), .I3 (vbat[2]), .O (n_68));
  MAO222CHD g1927__4319(.A1 (n_11), .B1 (n_4), .C1 (vbat[1]), .O
       (n_65));
  OA13CHD g1829__8428(.A1 (n_9), .B1 (n_63), .B2 (n_62), .B3 (ibat[4]),
       .O (n_64));
  MAOI1CHD g1943__5526(.A1 (n_60), .A2 (charge_time[2]), .B1
       (charge_time[2]), .B2 (n_60), .O (n_61));
  AN2CHD g1914__6783(.I1 (n_59), .I2 (n_13), .O (n_141));
  AN2CHD g1913__3680(.I1 (n_58), .I2 (n_12), .O (n_145));
  OR3EHD g1945__1617(.I1 (n_162), .I2 (n_57), .I3 (n_60), .O (n_138));
  AOI22BHD g1850__2802(.A1 (n_55), .A2 (tmax[1]), .B1 (n_54), .B2
       (tmax[0]), .O (n_56));
  NR8EHD g1873__1705(.I1 (charge_time[3]), .I2 (charge_time[6]), .I3
       (charge_time[1]), .I4 (charge_time[4]), .I5 (charge_time[5]),
       .I6 (charge_time[2]), .I7 (charge_time[7]), .I8
       (charge_time[0]), .O (n_53));
  NR2BHD g1752__5122(.I1 (n_119), .I2 (n_191), .O (cv));
  OAI12CHD g1881__8246(.A1 (n_48), .B1 (n_47), .B2 (tempmax[6]), .O
       (n_158));
  OR2B1CHD g1869__7098(.I1 (n_52), .B1 (state[1]), .O (n_89));
  AN2B1CHD g1857__6131(.I1 (n_51), .B1 (state[2]), .O (n_211));
  NR2CHD g1870__1881(.I1 (state[1]), .I2 (n_52), .O (n_208));
  ND2DHD g1942__5115(.I1 (n_50), .I2 (counter[2]), .O (n_124));
  ND3CHD g1885__7482(.I1 (n_48), .I2 (n_47), .I3 (tempmax[6]), .O
       (n_49));
  OR2EHD g1941__4733(.I1 (n_57), .I2 (n_60), .O (n_46));
  AOI22BHD g1949__6161(.A1 (n_55), .A2 (charge_time[0]), .B1 (n_54),
       .B2 (charge_time[1]), .O (n_45));
  OAI12CHD g1824__9315(.A1 (n_44), .B1 (n_2), .B2 (iend[6]), .O
       (n_129));
  AOI22BHD g1825__9945(.A1 (n_179), .A2 (tmax[7]), .B1 (n_164), .B2
       (tmax[6]), .O (n_78));
  ND2CHD g1826__2883(.I1 (n_191), .I2 (state[2]), .O (n_117));
  OR2B1CHD g1833__2346(.I1 (n_43), .B1 (counter[6]), .O (n_149));
  ND2CHD g1813__1666(.I1 (n_191), .I2 (en), .O (n_184));
  OAI12CHD g1882__7410(.A1 (n_42), .B1 (n_3), .B2 (tbat[6]), .O
       (n_160));
  NR2CHD g1839__6417(.I1 (tmax[6]), .I2 (n_164), .O (n_41));
  ND2CHD g1842__5477(.I1 (n_57), .I2 (tmax[2]), .O (n_40));
  OAI22CHD g1900__2398(.A1 (vbat[1]), .A2 (vbat[3]), .B1 (vbat[3]), .B2
       (vbat[2]), .O (n_39));
  NR2BHD g1915__5107(.I1 (vpreset[6]), .I2 (n_34), .O (n_38));
  OAI112BHD g1889__6260(.A1 (vbat[7]), .B1 (vbat[6]), .C1 (vbat[5]),
       .C2 (vbat[4]), .O (n_37));
  NR2CHD g1849__4319(.I1 (tmax[1]), .I2 (n_55), .O (n_36));
  NR2BHD g1928__8428(.I1 (vcutoff[6]), .I2 (n_34), .O (n_35));
  INVDHD g1867(.I (n_191), .O (n_33));
  ND2CHD g1846__5526(.I1 (n_32), .I2 (ibat[3]), .O (n_103));
  ND2CHD g1844__6783(.I1 (n_162), .I2 (tmax[3]), .O (n_115));
  AN2EHD g1845__3680(.I1 (n_166), .I2 (tmax[5]), .O (n_108));
  DFCRBEHD \state_reg[2] (.CK (clk), .D (nxt_state[2]), .RB (en), .Q
       (state[2]), .QB (UNCONNECTED));
  AN2CHD g1789__1617(.I1 (n_119), .I2 (rstz), .O (n_99));
  ND2CHD g1834__2802(.I1 (n_179), .I2 (tmax[7]), .O (n_31));
  XNR2EHD g1948__1705(.I1 (counter[0]), .I2 (counter[1]), .O (n_30));
  ND2CHD g1931__5122(.I1 (n_126), .I2 (vpreset[5]), .O (n_74));
  OR2CHD g1920__8246(.I1 (vbat[7]), .I2 (n_29), .O (n_58));
  OR2CHD g1921__7098(.I1 (vbat[7]), .I2 (n_28), .O (n_59));
  OR2CHD g1906__6131(.I1 (tempmax[5]), .I2 (n_27), .O (n_112));
  ND2CHD g1929__1881(.I1 (n_171), .I2 (vcutoff[3]), .O (n_83));
  ND2CHD g1930__5115(.I1 (n_171), .I2 (vpreset[3]), .O (n_67));
  ND2CHD g1908__7482(.I1 (n_27), .I2 (tempmin[5]), .O (n_110));
  ND2CHD g1932__4733(.I1 (n_126), .I2 (vcutoff[5]), .O (n_70));
  ND2CHD g1905__6161(.I1 (n_26), .I2 (tbat[3]), .O (n_106));
  ND2CHD g1907__9315(.I1 (n_25), .I2 (tempmin[3]), .O (n_86));
  DFCRBEHD \state_reg[1] (.CK (clk), .D (nxt_state[1]), .RB (en), .Q
       (state[1]), .QB (UNCONNECTED0));
  DFCRBEHD \state_reg[0] (.CK (clk), .D (nxt_state[0]), .RB (en), .Q
       (state[0]), .QB (UNCONNECTED1));
  OR2B1CHD g1880__9945(.I1 (tbat[7]), .B1 (tempmax[7]), .O (n_24));
  OR2B1CHD g1892__2883(.I1 (tbat[4]), .B1 (tempmin[4]), .O (n_23));
  OR2B1CHD g1891__2346(.I1 (tempmax[4]), .B1 (tbat[4]), .O (n_22));
  OR2B1CHD g1848__1666(.I1 (tmax[4]), .B1 (charge_time[4]), .O (n_21));
  OR2B1CHD g1822__7410(.I1 (ibat[7]), .B1 (iend[7]), .O (n_20));
  OR2B1CHD g1878__6417(.I1 (tempmin[7]), .B1 (tbat[7]), .O (n_19));
  OR2B1CHD g1894__5477(.I1 (tempmax[7]), .B1 (tbat[7]), .O (n_48));
  NR2CHD g1861__2398(.I1 (state[1]), .I2 (state[0]), .O (n_51));
  AN2B1CHD g1843__5107(.I1 (ibat[5]), .B1 (iend[5]), .O (n_63));
  OR2B1CHD g1895__6260(.I1 (tbat[7]), .B1 (tempmin[7]), .O (n_42));
  ND2CHD g1851__4319(.I1 (counter[4]), .I2 (counter[5]), .O (n_43));
  OR2B1CHD g1883__8428(.I1 (state[2]), .B1 (state[0]), .O (n_52));
  ND2DHD g1947__5526(.I1 (charge_time[0]), .I2 (charge_time[1]), .O
       (n_60));
  OR2B1CHD g1871__6783(.I1 (state[0]), .B1 (state[1]), .O (n_191));
  OR2B1CHD g1853__3680(.I1 (iend[0]), .B1 (ibat[0]), .O (n_18));
  AN2B1CHD g1903__1617(.I1 (tempmax[4]), .B1 (tbat[4]), .O (n_17));
  AN2B1CHD g1904__2802(.I1 (tbat[4]), .B1 (tempmin[4]), .O (n_16));
  OR2B1CHD g1916__1705(.I1 (tbat[0]), .B1 (tempmin[0]), .O (n_15));
  OR2B1CHD g1917__5122(.I1 (tempmax[0]), .B1 (tbat[0]), .O (n_14));
  OR2B1CHD g1918__8246(.I1 (vbat[6]), .B1 (vpreset[6]), .O (n_13));
  OR2B1CHD g1919__7098(.I1 (vbat[6]), .B1 (vcutoff[6]), .O (n_12));
  OR2B1CHD g1933__6131(.I1 (vbat[0]), .B1 (vcutoff[0]), .O (n_11));
  OR2B1CHD g1934__1881(.I1 (vbat[0]), .B1 (vpreset[0]), .O (n_10));
  OR2B1CHD g1832__5115(.I1 (ibat[5]), .B1 (iend[5]), .O (n_9));
  OR2B1CHD g1835__7482(.I1 (iend[7]), .B1 (ibat[7]), .O (n_44));
  ND2CHD g1816__4733(.I1 (charge_time[4]), .I2 (charge_time[5]), .O
       (n_132));
  AN2EHD g1946__6161(.I1 (counter[1]), .I2 (counter[0]), .O (n_50));
  ND2CHD g1790__9315(.I1 (en), .I2 (rstz), .O (n_189));
  INVCKDHD g1961(.I (tbat[1]), .O (n_8));
  INVCKDHD g1970(.I (tmax[7]), .O (n_7));
  INVCKDHD g1956(.I (tempmin[5]), .O (n_6));
  INVCKDHD g1955(.I (tempmin[1]), .O (n_5));
  INVCKDHD g1973(.I (vcutoff[1]), .O (n_4));
  INVCKDHD g1958(.I (tempmin[6]), .O (n_3));
  INVCKDHD g1957(.I (iend[3]), .O (n_32));
  INVCKDHD g1962(.I (vbat[6]), .O (n_34));
  INVCKDHD g1953(.I (vpreset[4]), .O (n_73));
  INVCKDHD g1975(.I (vcutoff[4]), .O (n_69));
  INVCKDHD g1978(.I (tbat[6]), .O (n_47));
  INVCKDHD g1952(.I (tempmax[3]), .O (n_26));
  INVDHD g1967(.I (charge_time[0]), .O (n_54));
  INVCKDHD g1960(.I (tbat[5]), .O (n_27));
  INVDHD g1983(.I (charge_time[4]), .O (n_147));
  INVDHD g1968(.I (charge_time[1]), .O (n_55));
  INVCKDHD g1985(.I (en), .O (n_119));
  INVDHD g1984(.I (charge_time[2]), .O (n_57));
  INVCKDHD g1954(.I (ibat[6]), .O (n_2));
  INVCKDHD g1969(.I (vpreset[1]), .O (n_1));
  INVCKDHD g1950(.I (ibat[1]), .O (n_0));
  INVCKDHD g1972(.I (ibat[2]), .O (n_102));
  INVCKDHD g1979(.I (tbat[2]), .O (n_105));
  INVCKDHD g1951(.I (iend[4]), .O (n_62));
  INVCKDHD g1971(.I (vcutoff[2]), .O (n_82));
  INVCKDHD g1977(.I (vpreset[7]), .O (n_28));
  INVCKDHD g1976(.I (tempmin[2]), .O (n_85));
  INVCKDHD g1980(.I (tbat[3]), .O (n_25));
  INVCKDHD g1974(.I (vpreset[2]), .O (n_66));
  INVCKDHD g1959(.I (vcutoff[7]), .O (n_29));
  INVCKDHD g1963(.I (vbat[3]), .O (n_171));
  INVDHD g1966(.I (charge_time[5]), .O (n_166));
  INVDHD g1964(.I (charge_time[7]), .O (n_179));
  INVCKDHD g1981(.I (vbat[5]), .O (n_126));
  INVDHD g1982(.I (charge_time[6]), .O (n_164));
  INVDHD g1965(.I (charge_time[3]), .O (n_162));
  TIE0DHD tie_0_cell(.O (logic_0_1_net));
endmodule

