
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec 10 2024 10:04:35 WET (Dec 10 2024 10:04:35 UTC)

// Verification Directory fv/BATCHARGERctr 

module BATCHARGERctr(cc, tc, cv, imonen, vmonen, tmonen, vtok, vbat,
     ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend, clk,
     en, rstz, dvdd, dgnd, si, se, so);
  input vtok, clk, en, rstz, si, se;
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  output cc, tc, cv, imonen, vmonen, tmonen, so;
  inout dvdd, dgnd;
  wire vtok, clk, en, rstz, si, se;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire cc, tc, cv, imonen, vmonen, tmonen, so;
  wire dvdd, dgnd;
  wire [2:0] nxt_state;
  wire [2:0] state;
  wire [7:0] counter;
  wire [7:0] charge_time;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_22, n_23, n_24, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_52;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_219, n_221, n_222, n_223, n_224, n_225, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_234, n_235;
  wire n_236, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252;
  wire n_333, n_334, n_335, n_336, n_337;
  assign so = vmonen;
  assign imonen = cv;
  QDFZRBEHD \nxt_state_reg[2] (.RB (en), .CK (clk), .D (n_250), .TD
       (nxt_state[1]), .SEL (se), .Q (nxt_state[2]));
  QDFZRBEHD \nxt_state_reg[0] (.RB (en), .CK (clk), .D (n_251), .TD
       (cv), .SEL (se), .Q (nxt_state[0]));
  QDFZRBEHD \nxt_state_reg[1] (.RB (en), .CK (clk), .D (n_252), .TD
       (nxt_state[0]), .SEL (se), .Q (nxt_state[1]));
  AN3EHD g2131__2398(.I1 (n_246), .I2 (rstz), .I3 (vtok), .O (n_252));
  AN3EHD g2134__5107(.I1 (n_248), .I2 (rstz), .I3 (vtok), .O (n_251));
  AN3EHD g2141__6260(.I1 (n_249), .I2 (rstz), .I3 (vtok), .O (n_250));
  AOI22BHD g2167__4319(.A1 (state[1]), .A2 (n_242), .B1 (n_247), .B2
       (n_244), .O (n_249));
  AOI22BHD g2170__8428(.A1 (state[1]), .A2 (n_240), .B1 (n_247), .B2
       (n_245), .O (n_248));
  AOI22BHD g2171__5526(.A1 (state[1]), .A2 (n_239), .B1 (n_247), .B2
       (n_241), .O (n_246));
  OAI22CHD g2182__6783(.A1 (n_235), .A2 (state[0]), .B1 (n_243), .B2
       (n_227), .O (n_245));
  OAI22CHD g2187__3680(.A1 (n_236), .A2 (state[0]), .B1 (n_243), .B2
       (n_226), .O (n_244));
  OAI22CHD g2189__1617(.A1 (n_336), .A2 (state[0]), .B1 (n_243), .B2
       (n_214), .O (n_242));
  OAI22CHD g2190__2802(.A1 (n_229), .A2 (n_243), .B1 (state[0]), .B2
       (n_232), .O (n_241));
  OAI12CHD g2191__1705(.A1 (n_238), .B1 (state[0]), .B2 (n_234), .O
       (n_240));
  OAI12CHD g2188__5122(.A1 (n_238), .B1 (state[0]), .B2 (n_230), .O
       (n_239));
  AN2EHD g2200__7098(.I1 (n_231), .I2 (n_154), .O (n_236));
  MXL2CHD g2203__6131(.S (n_222), .A (n_217), .B (n_52), .OB (n_235));
  OA13EHD g2207__1881(.A1 (n_224), .B1 (state[2]), .B2 (n_210), .B3
       (n_211), .O (n_234));
  AN2EHD g2198__5115(.I1 (n_231), .I2 (n_153), .O (n_232));
  AOI22BHD g2208__7482(.A1 (n_212), .A2 (n_228), .B1 (state[2]), .B2
       (n_206), .O (n_230));
  AOI12CHD g2201__4733(.A1 (state[2]), .B1 (n_228), .B2 (n_209), .O
       (n_229));
  NR3BHD g2204__6161(.I1 (n_225), .I2 (n_223), .I3 (state[2]), .O
       (n_227));
  NR3BHD g2205__9315(.I1 (n_225), .I2 (n_219), .I3 (state[2]), .O
       (n_226));
  OAI112BHD g2213__9945(.A1 (state[2]), .B1 (n_223), .C1 (n_215), .C2
       (n_221), .O (n_224));
  AO12EHD g2210__2883(.A1 (n_222), .B1 (n_216), .B2 (n_221), .O
       (n_231));
  ND2CHD g2219__7410(.I1 (n_216), .I2 (n_205), .O (n_217));
  OAI13BHD g2196__6417(.A1 (state[0]), .B1 (state[2]), .B2 (n_215), .B3
       (n_213), .O (n_238));
  AN3B2BHD g2206__5477(.I1 (n_213), .B1 (state[2]), .B2 (n_215), .O
       (n_214));
  INVDHD g2223(.I (n_211), .O (n_212));
  INVDHD g2224(.I (n_223), .O (n_210));
  OR2B1CHD g2214__2398(.I1 (n_215), .B1 (n_225), .O (n_209));
  NR2CHD g2225__5107(.I1 (n_215), .I2 (n_208), .O (n_211));
  OR2B1CHD g2217__6260(.I1 (n_215), .B1 (nxt_state[1]), .O (n_228));
  NR2CHD g2230__4319(.I1 (n_215), .I2 (state[2]), .O (n_216));
  OR2B1CHD g2227__8428(.I1 (n_215), .B1 (nxt_state[2]), .O (n_219));
  OR2B1CHD g2226__5526(.I1 (n_215), .B1 (nxt_state[0]), .O (n_223));
  NR6EHD g2235__6783(.I1 (tempmax[2]), .I2 (tempmax[4]), .I3 (n_17),
       .I4 (tempmax[3]), .I5 (tempmax[5]), .I6 (n_207), .O (n_215));
  QDFZHHD \counter_reg[7] (.CK (clk), .D (n_202), .TD (counter[6]),
       .SEL (se), .Q (counter[7]));
  QDFZHHD \charge_time_reg[3] (.CK (clk), .D (n_196), .TD
       (charge_time[2]), .SEL (se), .Q (charge_time[3]));
  QDFZHHD \charge_time_reg[5] (.CK (clk), .D (n_200), .TD
       (charge_time[4]), .SEL (se), .Q (charge_time[5]));
  QDFZHHD \charge_time_reg[6] (.CK (clk), .D (n_203), .TD
       (charge_time[5]), .SEL (se), .Q (charge_time[6]));
  OR3CHD g2254__3680(.I1 (tempmax[0]), .I2 (tempmax[1]), .I3 (n_204),
       .O (n_207));
  QDFZHHD \charge_time_reg[7] (.CK (clk), .D (n_198), .TD
       (charge_time[6]), .SEL (se), .Q (charge_time[7]));
  QDFZHHD \charge_time_reg[1] (.CK (clk), .D (n_194), .TD
       (charge_time[0]), .SEL (se), .Q (charge_time[1]));
  QDFZHHD \charge_time_reg[2] (.CK (clk), .D (n_195), .TD
       (charge_time[1]), .SEL (se), .Q (charge_time[2]));
  QDFZHHD \charge_time_reg[4] (.CK (clk), .D (n_197), .TD
       (charge_time[3]), .SEL (se), .Q (charge_time[4]));
  ND2CHD g2216__1617(.I1 (nxt_state[1]), .I2 (n_221), .O (n_206));
  QDFZHHD \counter_reg[6] (.CK (clk), .D (n_192), .TD (counter[5]),
       .SEL (se), .Q (counter[6]));
  QDFZHHD \charge_time_reg[0] (.CK (clk), .D (n_193), .TD (cc), .SEL
       (se), .Q (charge_time[0]));
  QDFZHHD \counter_reg[5] (.CK (clk), .D (n_191), .TD (counter[4]),
       .SEL (se), .Q (counter[5]));
  OR3B2CHD g2221__2802(.I1 (n_151), .B1 (n_189), .B2 (n_167), .O
       (n_213));
  INVCKDHD g2232(.I (n_205), .O (n_221));
  QDFZHHD \counter_reg[3] (.CK (clk), .D (n_186), .TD (counter[2]),
       .SEL (se), .Q (counter[3]));
  NR2BHD g2288__1705(.I1 (n_160), .I2 (n_190), .O (n_204));
  QDFZHHD \counter_reg[4] (.CK (clk), .D (n_333), .TD (counter[3]),
       .SEL (se), .Q (counter[4]));
  OA112EHD g2145__5122(.A1 (n_188), .B1 (n_201), .C1 (n_199), .C2
       (charge_time[6]), .O (n_203));
  OA112EHD g2152__8246(.A1 (n_180), .B1 (n_201), .C1 (n_23), .C2
       (counter[7]), .O (n_202));
  OA112EHD g2124__7098(.A1 (n_184), .B1 (n_201), .C1 (n_199), .C2
       (charge_time[5]), .O (n_200));
  AO2222BHD g2234__6131(.A1 (n_174), .A2 (n_127), .B1 (n_35), .B2
       (n_38), .C1 (n_7), .C2 (vbat[7]), .D1 (n_126), .D2 (n_124), .O
       (n_205));
  AO2222BHD g2231__1881(.A1 (n_178), .A2 (n_150), .B1 (n_92), .B2
       (n_42), .C1 (n_32), .C2 (vbat[7]), .D1 (n_149), .D2 (n_132), .O
       (n_225));
  OA112EHD g2139__5115(.A1 (n_185), .B1 (n_201), .C1 (n_199), .C2
       (charge_time[7]), .O (n_198));
  OA112EHD g2136__7482(.A1 (n_181), .B1 (n_201), .C1 (n_199), .C2
       (charge_time[4]), .O (n_197));
  OA112EHD g2135__4733(.A1 (n_182), .B1 (n_201), .C1 (n_199), .C2
       (charge_time[3]), .O (n_196));
  OA112EHD g2140__6161(.A1 (n_183), .B1 (n_201), .C1 (n_199), .C2
       (charge_time[2]), .O (n_195));
  OA112EHD g2142__9315(.A1 (n_187), .B1 (n_201), .C1 (n_199), .C2
       (charge_time[1]), .O (n_194));
  AOI112BHD g2144__9945(.A1 (n_172), .B1 (n_169), .C1 (n_199), .C2
       (charge_time[0]), .O (n_193));
  OA112EHD g2146__2883(.A1 (n_176), .B1 (n_201), .C1 (n_23), .C2
       (counter[6]), .O (n_192));
  OA112EHD g2151__2346(.A1 (n_175), .B1 (n_201), .C1 (n_23), .C2
       (counter[5]), .O (n_191));
  AN4B1BHD g2297__1666(.I1 (n_171), .I2 (n_118), .I3 (n_27), .B1
       (n_159), .O (n_190));
  AOI22BHD g2228__7410(.A1 (n_177), .A2 (n_134), .B1 (n_166), .B2
       (n_148), .O (n_189));
  QDFZHHD \counter_reg[0] (.CK (clk), .D (n_170), .TD (charge_time[7]),
       .SEL (se), .Q (counter[0]));
  QDFZHHD \counter_reg[2] (.CK (clk), .D (n_168), .TD (counter[1]),
       .SEL (se), .Q (counter[2]));
  QDFZHHD \counter_reg[1] (.CK (clk), .D (n_164), .TD (counter[0]),
       .SEL (se), .Q (counter[1]));
  OAI112BHD g2154__6417(.A1 (n_199), .B1 (n_143), .C1 (n_142), .C2
       (charge_time[6]), .O (n_188));
  OAI112BHD g2153__5477(.A1 (n_199), .B1 (n_60), .C1 (n_65), .C2
       (charge_time[1]), .O (n_187));
  OA112CHD g2150__2398(.A1 (n_201), .B1 (n_163), .C1 (n_23), .C2
       (counter[3]), .O (n_186));
  OAI112BHD g2156__5107(.A1 (n_199), .B1 (n_158), .C1 (n_157), .C2
       (charge_time[7]), .O (n_185));
  OAI112BHD g2157__6260(.A1 (n_199), .B1 (n_146), .C1 (n_145), .C2
       (charge_time[5]), .O (n_184));
  OAI112BHD g2160__4319(.A1 (n_199), .B1 (n_71), .C1 (n_70), .C2
       (charge_time[2]), .O (n_183));
  OAI112BHD g2159__8428(.A1 (n_199), .B1 (n_115), .C1 (n_114), .C2
       (charge_time[3]), .O (n_182));
  OAI112BHD g2158__5526(.A1 (n_199), .B1 (n_120), .C1 (n_122), .C2
       (charge_time[4]), .O (n_181));
  OAI112BHD g2168__6783(.A1 (n_162), .B1 (state[1]), .C1 (n_161), .C2
       (counter[7]), .O (n_180));
  OAI112BHD g2240__1617(.A1 (n_144), .B1 (n_86), .C1 (n_173), .C2
       (vpreset[3]), .O (n_178));
  OAI112BHD g2242__2802(.A1 (n_141), .B1 (n_90), .C1 (n_31), .C2
       (ibat[3]), .O (n_177));
  OAI112BHD g2162__1705(.A1 (n_140), .B1 (state[1]), .C1 (n_139), .C2
       (counter[6]), .O (n_176));
  OAI112BHD g2169__5122(.A1 (n_137), .B1 (state[1]), .C1 (n_136), .C2
       (counter[5]), .O (n_175));
  OAI112BHD g2255__8246(.A1 (n_138), .B1 (n_76), .C1 (n_173), .C2
       (vcutoff[3]), .O (n_174));
  NR2CHD g2164__7098(.I1 (charge_time[0]), .I2 (n_199), .O (n_172));
  OAI112BHD g2300__6131(.A1 (n_152), .B1 (n_106), .C1 (n_45), .C2
       (tempmin[3]), .O (n_171));
  AOI112BHD g2148__1881(.A1 (n_169), .B1 (n_103), .C1 (state[1]), .C2
       (counter[0]), .O (n_170));
  OA112CHD g2149__5115(.A1 (n_201), .B1 (n_135), .C1 (n_23), .C2
       (counter[2]), .O (n_168));
  QDFZRBCHD cv_reg(.RB (en), .CK (clk), .D (n_117), .TD (counter[7]),
       .SEL (se), .Q (cv));
  AOI222BHD g2237__7482(.A1 (n_93), .A2 (n_337), .B1 (n_147), .B2
       (n_131), .C1 (charge_time[7]), .C2 (n_30), .O (n_167));
  OAI112BHD g2239__4733(.A1 (n_125), .B1 (n_113), .C1 (n_29), .C2
       (tmax[3]), .O (n_166));
  QDFZRBCHD vmonen_reg(.RB (en), .CK (clk), .D (n_97), .TD (tmonen),
       .SEL (se), .Q (vmonen));
  QDFZRBCHD tc_reg(.RB (en), .CK (clk), .D (n_102), .TD (state[2]),
       .SEL (se), .Q (tc));
  OA112CHD g2147__9315(.A1 (n_201), .B1 (n_121), .C1 (n_23), .C2
       (counter[1]), .O (n_164));
  OAI112BHD g2166__9945(.A1 (n_111), .B1 (state[1]), .C1 (n_110), .C2
       (counter[3]), .O (n_163));
  ND2CHD g2183__2883(.I1 (n_161), .I2 (counter[7]), .O (n_162));
  OAI112BHD g2298__2346(.A1 (n_67), .B1 (n_20), .C1 (n_119), .C2
       (n_159), .O (n_160));
  ND2DHD g2172__1666(.I1 (n_157), .I2 (charge_time[7]), .O (n_158));
  AN4B1BHD g2179__7410(.I1 (counter[6]), .I2 (counter[5]), .I3
       (counter[4]), .B1 (n_109), .O (n_199));
  QDFZRBCHD cc_reg(.RB (en), .CK (clk), .D (n_72), .TD (si), .SEL (se),
       .Q (cc));
  OAI12CHD g2211__6417(.A1 (n_222), .B1 (n_23), .B2 (n_5), .O (n_154));
  OAI12CHD g2212__5477(.A1 (n_222), .B1 (n_23), .B2 (n_8), .O (n_153));
  OAI112BHD g2305__2398(.A1 (n_94), .B1 (n_105), .C1 (n_104), .C2
       (tbat[2]), .O (n_152));
  OAI112BHD g2238__5107(.A1 (n_95), .B1 (n_16), .C1 (n_100), .C2
       (n_133), .O (n_151));
  OA112CHD g2243__6260(.A1 (n_149), .B1 (n_82), .C1 (n_81), .C2
       (vbat[4]), .O (n_150));
  OA112EHD g2244__4319(.A1 (n_147), .B1 (n_130), .C1 (charge_time[4]),
       .C2 (n_129), .O (n_148));
  ND2DHD g2177__8428(.I1 (n_145), .I2 (charge_time[5]), .O (n_146));
  OAI112BHD g2257__5526(.A1 (n_80), .B1 (n_85), .C1 (n_84), .C2
       (vbat[2]), .O (n_144));
  QDFZRBCHD tmonen_reg(.RB (en), .CK (clk), .D (n_73), .TD (tc), .SEL
       (se), .Q (tmonen));
  ND2DHD g2173__6783(.I1 (n_142), .I2 (charge_time[6]), .O (n_143));
  OAI112BHD g2252__3680(.A1 (n_87), .B1 (n_89), .C1 (n_88), .C2
       (iend[2]), .O (n_141));
  ND2CHD g2181__1617(.I1 (n_139), .I2 (counter[6]), .O (n_140));
  OAI112BHD g2275__2802(.A1 (n_91), .B1 (n_75), .C1 (n_74), .C2
       (vbat[2]), .O (n_138));
  ND2DHD g2185__1705(.I1 (n_136), .I2 (counter[5]), .O (n_137));
  OAI112BHD g2165__5122(.A1 (n_69), .B1 (state[1]), .C1 (n_68), .C2
       (counter[2]), .O (n_135));
  AOI112BHD g2241__8246(.A1 (n_133), .B1 (n_99), .C1 (n_98), .C2
       (ibat[4]), .O (n_134));
  OAI12CHD g2256__7098(.A1 (n_83), .B1 (n_123), .B2 (vpreset[5]), .O
       (n_132));
  AO13EHD g2253__6131(.A1 (n_44), .B1 (charge_time[4]), .B2 (n_130),
       .B3 (n_129), .O (n_131));
  OA112CHD g2258__5115(.A1 (n_126), .B1 (n_78), .C1 (n_77), .C2
       (vbat[4]), .O (n_127));
  OAI112BHD g2259__7482(.A1 (n_112), .B1 (n_12), .C1 (n_66), .C2
       (n_40), .O (n_125));
  OAI12CHD g2273__4733(.A1 (n_79), .B1 (n_123), .B2 (vcutoff[5]), .O
       (n_124));
  OR3B1EHD g2192__6161(.I1 (n_107), .I2 (n_122), .B1 (charge_time[6]),
       .O (n_157));
  OR3B1EHD g2197__9315(.I1 (n_108), .I2 (n_128), .B1 (counter[6]), .O
       (n_161));
  INVDHD g2176(.I (n_201), .O (n_169));
  OAI112BHD g2163__9945(.A1 (n_48), .B1 (state[1]), .C1 (n_47), .C2
       (counter[1]), .O (n_121));
  ND2DHD g2319__2883(.I1 (n_122), .I2 (charge_time[4]), .O (n_120));
  OR2B1CHD g2315__2346(.I1 (n_128), .B1 (counter[4]), .O (n_136));
  OR2B1CHD g2316__1666(.I1 (n_122), .B1 (charge_time[4]), .O (n_145));
  AOI12CHD g2222__7410(.A1 (n_50), .B1 (n_61), .B2 (n_123), .O (n_222));
  QDFZRSBEHD \state_reg[2] (.RB (n_18), .SB (n_33), .CK (clk), .D
       (nxt_state[2]), .TD (state[1]), .SEL (se), .Q (state[2]));
  QDFZRSBEHD \state_reg[0] (.RB (n_13), .SB (n_37), .CK (clk), .D
       (nxt_state[0]), .TD (nxt_state[2]), .SEL (se), .Q (state[0]));
  QDFZRSBEHD \state_reg[1] (.RB (n_19), .SB (n_49), .CK (clk), .D
       (nxt_state[1]), .TD (state[0]), .SEL (se), .Q (state[1]));
  AOI22BHD g2304__6417(.A1 (n_24), .A2 (n_118), .B1 (n_46), .B2
       (tbat[5]), .O (n_119));
  INVDHD g2175(.I (n_116), .O (n_117));
  ND2DHD g2174__5477(.I1 (n_114), .I2 (charge_time[3]), .O (n_115));
  OR3B2CHD g2274__2398(.I1 (tmax[2]), .B1 (charge_time[2]), .B2
       (n_112), .O (n_113));
  ND2DHD g2184__5107(.I1 (n_110), .I2 (counter[3]), .O (n_111));
  OR3B2CHD g2195__6260(.I1 (n_128), .B1 (state[1]), .B2 (counter[7]),
       .O (n_109));
  OR2EHD g2193__4319(.I1 (n_108), .I2 (n_128), .O (n_139));
  OR2EHD g2186__8428(.I1 (n_107), .I2 (n_122), .O (n_142));
  AOI22BHD g2180__5526(.A1 (n_101), .A2 (n_247), .B1 (state[2]), .B2
       (state[1]), .O (n_201));
  ND3CHD g2308__6783(.I1 (n_105), .I2 (n_104), .I3 (tbat[2]), .O
       (n_106));
  NR2CHD g2155__3680(.I1 (counter[0]), .I2 (n_23), .O (n_103));
  NR2BHD g2130__1617(.I1 (n_247), .I2 (n_101), .O (n_102));
  OA13CHD g2245__2802(.A1 (n_26), .B1 (n_99), .B2 (n_98), .B3
       (ibat[4]), .O (n_100));
  OAI12CHD g2132__1705(.A1 (n_101), .B1 (state[2]), .B2 (state[1]), .O
       (n_97));
  OR3B2CHD g2248__5122(.I1 (ibat[6]), .B1 (n_62), .B2 (iend[6]), .O
       (n_95));
  MAO222CHD g2309__8246(.A1 (n_22), .B1 (n_0), .C1 (tbat[1]), .O
       (n_94));
  AN2EHD g2249__7098(.I1 (n_93), .I2 (n_14), .O (n_147));
  AN2CHD g2250__6131(.I1 (n_92), .I2 (n_15), .O (n_149));
  MAO222CHD g2291__1881(.A1 (n_11), .B1 (n_2), .C1 (vbat[1]), .O
       (n_91));
  ND3CHD g2270__5115(.I1 (n_89), .I2 (n_88), .I3 (iend[2]), .O (n_90));
  MAO222CHD g2269__7482(.A1 (n_9), .B1 (n_4), .C1 (iend[1]), .O (n_87));
  ND3CHD g2271__4733(.I1 (n_85), .I2 (n_84), .I3 (vbat[2]), .O (n_86));
  ND3CHD g2272__6161(.I1 (n_82), .I2 (n_81), .I3 (vbat[4]), .O (n_83));
  MAO222CHD g2276__9315(.A1 (n_10), .B1 (n_1), .C1 (vbat[1]), .O
       (n_80));
  ND3CHD g2285__9945(.I1 (n_78), .I2 (n_77), .I3 (vbat[4]), .O (n_79));
  ND3CHD g2290__2883(.I1 (n_75), .I2 (n_74), .I3 (vbat[2]), .O (n_76));
  ND2CHD g2178__2346(.I1 (n_23), .I2 (state[1]), .O (n_116));
  OAI12CHD g2133__1666(.A1 (state[2]), .B1 (n_247), .B2 (state[0]), .O
       (n_73));
  NR3BHD g2143__7410(.I1 (state[2]), .I2 (state[1]), .I3 (n_243), .O
       (n_72));
  ND2DHD g2321__6417(.I1 (n_70), .I2 (charge_time[2]), .O (n_71));
  ND2DHD g2322__5477(.I1 (n_68), .I2 (counter[2]), .O (n_69));
  OR2B1CHD g2320__2398(.I1 (n_70), .B1 (charge_time[2]), .O (n_114));
  OR3B2CHD g2323__5107(.I1 (n_70), .B1 (charge_time[2]), .B2
       (charge_time[3]), .O (n_122));
  OR3B2CHD g2324__6260(.I1 (n_68), .B1 (counter[2]), .B2 (counter[3]),
       .O (n_128));
  ND3CHD g2303__4319(.I1 (n_64), .I2 (n_63), .I3 (tbat[6]), .O (n_67));
  AOI22BHD g2289__8428(.A1 (n_39), .A2 (tmax[1]), .B1 (n_65), .B2
       (tmax[0]), .O (n_66));
  OAI12CHD g2302__5526(.A1 (n_64), .B1 (n_63), .B2 (tbat[6]), .O
       (n_159));
  OR2B1CHD g2318__6783(.I1 (n_68), .B1 (counter[2]), .O (n_110));
  AOI22BHD g2277__3680(.A1 (n_41), .A2 (vcutoff[6]), .B1 (n_34), .B2
       (vcutoff[7]), .O (n_126));
  OAI12CHD g2251__1617(.A1 (n_62), .B1 (n_3), .B2 (iend[6]), .O
       (n_133));
  NR8EHD g2233__2802(.I1 (charge_time[3]), .I2 (charge_time[6]), .I3
       (charge_time[1]), .I4 (charge_time[4]), .I5 (charge_time[5]),
       .I6 (charge_time[2]), .I7 (charge_time[7]), .I8
       (charge_time[0]), .O (n_208));
  OAI22CHD g2236__1705(.A1 (vbat[1]), .A2 (vbat[3]), .B1 (vbat[3]), .B2
       (vbat[2]), .O (n_61));
  ND2DHD g2328__5122(.I1 (n_65), .I2 (charge_time[1]), .O (n_60));
  INVDHD g2367(.I (state[2]), .O (n_23));
  ND2CHD g2220__8246(.I1 (state[2]), .I2 (nxt_state[0]), .O (n_52));
  OAI112BHD g2229__7098(.A1 (vbat[7]), .B1 (vbat[6]), .C1 (vbat[5]),
       .C2 (vbat[4]), .O (n_50));
  ND2CHD g2126__6131(.I1 (nxt_state[1]), .I2 (n_36), .O (n_49));
  ND2DHD g2327__1881(.I1 (n_47), .I2 (counter[1]), .O (n_48));
  OR2CHD g2310__5115(.I1 (tbat[5]), .I2 (n_46), .O (n_118));
  ND2CHD g2312__7482(.I1 (n_45), .I2 (tempmin[3]), .O (n_105));
  ND2CHD g2283__4733(.I1 (n_123), .I2 (vpreset[5]), .O (n_82));
  NR2CHD g2260__6161(.I1 (tmax[5]), .I2 (n_28), .O (n_44));
  NR2BHD g2263__9945(.I1 (vpreset[6]), .I2 (n_41), .O (n_42));
  NR2CHD g2287__2883(.I1 (tmax[1]), .I2 (n_39), .O (n_40));
  NR2BHD g2286__2346(.I1 (vcutoff[6]), .I2 (n_41), .O (n_38));
  ND2CHD g2137__1666(.I1 (nxt_state[0]), .I2 (n_36), .O (n_37));
  ND2CHD g2279__7410(.I1 (n_34), .I2 (vcutoff[7]), .O (n_35));
  ND2CHD g2125__6417(.I1 (nxt_state[2]), .I2 (n_36), .O (n_33));
  OR2CHD g2267__5477(.I1 (vbat[7]), .I2 (n_32), .O (n_92));
  ND2CHD g2284__2398(.I1 (n_173), .I2 (vpreset[3]), .O (n_85));
  ND2CHD g2280__5107(.I1 (n_31), .I2 (ibat[3]), .O (n_89));
  OR2EHD g2268__6260(.I1 (n_30), .I2 (charge_time[7]), .O (n_93));
  ND2CHD g2292__4319(.I1 (n_29), .I2 (tmax[3]), .O (n_112));
  ND2CHD g2294__8428(.I1 (n_173), .I2 (vcutoff[3]), .O (n_75));
  ND2CHD g2295__5526(.I1 (n_123), .I2 (vcutoff[5]), .O (n_78));
  ND2CHD g2282__6783(.I1 (n_28), .I2 (tmax[5]), .O (n_130));
  ND2CHD g2194__3680(.I1 (n_243), .I2 (state[2]), .O (n_101));
  OR2B1CHD g2306__1617(.I1 (tbat[4]), .B1 (tempmin[4]), .O (n_27));
  OR2B1CHD g2264__2802(.I1 (ibat[5]), .B1 (iend[5]), .O (n_26));
  AN2B1CHD g2311__1705(.I1 (tbat[4]), .B1 (tempmin[4]), .O (n_24));
  OR2B1CHD g2313__5122(.I1 (tbat[0]), .B1 (tempmin[0]), .O (n_22));
  OR2B1CHD g2307__8246(.I1 (tbat[7]), .B1 (tempmin[7]), .O (n_64));
  ND2CHD g2209__7098(.I1 (counter[4]), .I2 (counter[5]), .O (n_108));
  ND2CHD g2202__6131(.I1 (charge_time[4]), .I2 (charge_time[5]), .O
       (n_107));
  ND2CHD g2326__1881(.I1 (counter[0]), .I2 (counter[1]), .O (n_68));
  ND2CHD g2325__5115(.I1 (charge_time[0]), .I2 (charge_time[1]), .O
       (n_70));
  OR2B1CHD g2301__7482(.I1 (tempmin[7]), .B1 (tbat[7]), .O (n_20));
  OR2CHD g2128__4733(.I1 (en), .I2 (nxt_state[1]), .O (n_19));
  OR2CHD g2129__6161(.I1 (en), .I2 (nxt_state[2]), .O (n_18));
  OR2CHD g2246__9315(.I1 (tempmax[6]), .I2 (tempmax[7]), .O (n_17));
  OR2B1CHD g2247__9945(.I1 (ibat[7]), .B1 (iend[7]), .O (n_16));
  OR2B1CHD g2261__2883(.I1 (vbat[6]), .B1 (vpreset[6]), .O (n_15));
  OR2B1CHD g2265__2346(.I1 (charge_time[6]), .B1 (tmax[6]), .O (n_14));
  OR2CHD g2127__1666(.I1 (en), .I2 (nxt_state[0]), .O (n_13));
  OR2B1CHD g2278__7410(.I1 (charge_time[2]), .B1 (tmax[2]), .O (n_12));
  OR2B1CHD g2299__6417(.I1 (vbat[0]), .B1 (vcutoff[0]), .O (n_11));
  OR2B1CHD g2293__5477(.I1 (vbat[0]), .B1 (vpreset[0]), .O (n_10));
  OR2B1CHD g2296__2398(.I1 (iend[0]), .B1 (ibat[0]), .O (n_9));
  AN2B1CHD g2281__5107(.I1 (ibat[5]), .B1 (iend[5]), .O (n_99));
  OR2B1CHD g2266__6260(.I1 (iend[7]), .B1 (ibat[7]), .O (n_62));
  INVDHD g2338(.I (nxt_state[1]), .O (n_8));
  INVCKDHD g2332(.I (vcutoff[7]), .O (n_7));
  INVDHD g2357(.I (nxt_state[2]), .O (n_5));
  INVCKDHD g2361(.I (charge_time[5]), .O (n_28));
  INVCKDHD g2331(.I (tmax[4]), .O (n_129));
  INVCKDHD g2346(.I (tmax[7]), .O (n_30));
  INVCKDHD g2343(.I (iend[4]), .O (n_98));
  INVCKDHD g2341(.I (charge_time[1]), .O (n_39));
  INVCKDHD g2329(.I (tempmin[5]), .O (n_46));
  INVCKDHD g2354(.I (vpreset[4]), .O (n_81));
  INVDHD g2336(.I (counter[0]), .O (n_47));
  INVCKDHD g2350(.I (vpreset[7]), .O (n_32));
  INVCKDHD g2340(.I (charge_time[3]), .O (n_29));
  INVCKDHD g2356(.I (vbat[6]), .O (n_41));
  INVDHD g2360(.I (charge_time[0]), .O (n_65));
  INVCKDHD g2359(.I (vbat[5]), .O (n_123));
  INVDHD g2363(.I (state[1]), .O (n_247));
  INVCKDHD g2333(.I (ibat[1]), .O (n_4));
  INVCKDHD g2344(.I (ibat[6]), .O (n_3));
  INVCKDHD g2353(.I (vcutoff[1]), .O (n_2));
  INVCKDHD g2348(.I (vpreset[1]), .O (n_1));
  INVCKDHD g2330(.I (tempmin[1]), .O (n_0));
  INVCKDHD g2352(.I (vpreset[2]), .O (n_84));
  INVCKDHD g2334(.I (vcutoff[2]), .O (n_74));
  INVCKDHD g2349(.I (tempmin[6]), .O (n_63));
  INVCKDHD g2345(.I (tbat[3]), .O (n_45));
  INVCKDHD g2355(.I (iend[3]), .O (n_31));
  INVCKDHD g2358(.I (vbat[7]), .O (n_34));
  INVCKDHD g2351(.I (vcutoff[4]), .O (n_77));
  INVCKDHD g2347(.I (ibat[2]), .O (n_88));
  INVCKDHD g2335(.I (tempmin[2]), .O (n_104));
  INVCKDHD g2362(.I (en), .O (n_36));
  INVCKDHD g2337(.I (vbat[3]), .O (n_173));
  INVDHD g2342(.I (state[0]), .O (n_243));
  OAI12CHD g2404(.A1 (n_334), .B1 (n_335), .B2 (n_116), .O (n_333));
  ND3CHD g2405(.I1 (n_201), .I2 (counter[4]), .I3 (n_247), .O (n_334));
  XOR2EHD g2406(.I1 (n_128), .I2 (counter[4]), .O (n_335));
  MUXB2CHD g2407(.S (state[2]), .A (n_208), .B (n_221), .EB (n_219), .O
       (n_336));
  AN2B1CHD g2(.I1 (charge_time[6]), .B1 (tmax[6]), .O (n_337));
endmodule

