
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec  9 2024 22:32:51 WET (Dec  9 2024 22:32:51 UTC)

// Verification Directory fv/BATCHARGERctr 

module BATCHARGERctr(cc, tc, cv, imonen, vmonen, tmonen, vtok, vbat,
     ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend, clk,
     en, rstz, dvdd, dgnd, si, se, so);
  input vtok, clk, en, rstz, si, se;
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  output cc, tc, cv, imonen, vmonen, tmonen, so;
  inout dvdd, dgnd;
  wire vtok, clk, en, rstz, si, se;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire cc, tc, cv, imonen, vmonen, tmonen, so;
  wire dvdd, dgnd;
  wire [2:0] nxt_state;
  wire [7:0] counter;
  wire [7:0] charge_time;
  wire [2:0] state;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_118, n_119, n_120, n_122, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_227, n_228, n_229, n_230, n_232, n_313;
  wire n_314, n_315;
  assign imonen = cv;
  QDFZHHD \nxt_state_reg[1] (.CK (clk), .D (n_232), .TD (nxt_state[0]),
       .SEL (se), .Q (nxt_state[1]));
  AO2222CHD g1768__2398(.A1 (n_313), .A2 (n_218), .B1 (n_217), .B2
       (n_208), .C1 (n_230), .C2 (n_210), .D1 (nxt_state[1]), .D2
       (n_228), .O (n_232));
  QDFZHHD \nxt_state_reg[0] (.CK (clk), .D (n_227), .TD (counter[7]),
       .SEL (se), .Q (nxt_state[0]));
  QDFZHHD \nxt_state_reg[2] (.CK (clk), .D (n_229), .TD (nxt_state[1]),
       .SEL (se), .Q (nxt_state[2]));
  AO12EHD g1761__6260(.A1 (n_225), .B1 (nxt_state[2]), .B2 (n_228), .O
       (n_229));
  AO12EHD g1762__4319(.A1 (n_222), .B1 (nxt_state[0]), .B2 (n_228), .O
       (n_227));
  OAI13BHD g1788__5526(.A1 (n_224), .B1 (n_195), .B2 (n_223), .B3
       (n_215), .O (n_225));
  AO13EHD g1787__6783(.A1 (n_230), .B1 (n_211), .B2 (n_216), .B3
       (n_221), .O (n_222));
  NR2CHD g1804__3680(.I1 (n_219), .I2 (n_220), .O (n_230));
  OR2B1CHD g1815__1617(.I1 (n_220), .B1 (n_219), .O (n_224));
  NR2BHD g1796__2802(.I1 (n_217), .I2 (n_228), .O (n_218));
  ND3CHD g1831__1705(.I1 (n_214), .I2 (n_216), .I3 (n_221), .O (n_220));
  NR2CHD g1805__5122(.I1 (n_215), .I2 (n_216), .O (n_228));
  NR3BHD g1808__8246(.I1 (n_215), .I2 (n_223), .I3 (n_315), .O (n_217));
  INVDHD g1836(.I (n_223), .O (n_216));
  OAI13BHD g1841__7098(.A1 (en), .B1 (n_139), .B2 (n_214), .B3 (n_213),
       .O (n_223));
  QDFZHHD \charge_time_reg[6] (.CK (clk), .D (n_209), .TD
       (charge_time[5]), .SEL (se), .Q (charge_time[6]));
  QDFZHHD \charge_time_reg[7] (.CK (clk), .D (n_206), .TD
       (charge_time[6]), .SEL (se), .Q (charge_time[7]));
  QDFZHHD \charge_time_reg[1] (.CK (clk), .D (n_203), .TD
       (charge_time[0]), .SEL (se), .Q (charge_time[1]));
  QDFZHHD \charge_time_reg[0] (.CK (clk), .D (n_200), .TD (si), .SEL
       (se), .Q (charge_time[0]));
  QDFZHHD \charge_time_reg[3] (.CK (clk), .D (n_199), .TD
       (charge_time[2]), .SEL (se), .Q (charge_time[3]));
  QDFZHHD \charge_time_reg[2] (.CK (clk), .D (n_201), .TD
       (charge_time[1]), .SEL (se), .Q (charge_time[2]));
  QDFZHHD \charge_time_reg[5] (.CK (clk), .D (n_198), .TD
       (charge_time[4]), .SEL (se), .Q (charge_time[5]));
  QDFZHHD \charge_time_reg[4] (.CK (clk), .D (n_202), .TD
       (charge_time[3]), .SEL (se), .Q (charge_time[4]));
  INVCKDHD g1847(.I (n_215), .O (n_221));
  ND2CHD g1854__6131(.I1 (n_212), .I2 (n_314), .O (n_213));
  OR3B2CHD g1852__1881(.I1 (n_207), .B1 (vtok), .B2 (rstz), .O (n_215));
  AOI22BHD g1859__5115(.A1 (n_211), .A2 (n_210), .B1 (n_92), .B2
       (n_197), .O (n_212));
  QDFZHHD \counter_reg[5] (.CK (clk), .D (n_194), .TD (counter[4]),
       .SEL (se), .Q (counter[5]));
  QDFZHHD \counter_reg[7] (.CK (clk), .D (n_189), .TD (counter[6]),
       .SEL (se), .Q (counter[7]));
  QDFZHHD \counter_reg[6] (.CK (clk), .D (n_196), .TD (counter[5]),
       .SEL (se), .Q (counter[6]));
  OAI22CHD g1769__7482(.A1 (n_205), .A2 (n_168), .B1 (n_167), .B2
       (n_204), .O (n_209));
  AOI112BHD g1801__4733(.A1 (n_191), .B1 (n_155), .C1 (n_177), .C2
       (n_134), .O (n_208));
  OAI22CHD g1855__6161(.A1 (n_162), .A2 (n_190), .B1 (n_192), .B2
       (n_160), .O (n_207));
  OAI22CHD g1773__9315(.A1 (n_205), .A2 (n_184), .B1 (n_183), .B2
       (n_204), .O (n_206));
  OAI22CHD g1772__9945(.A1 (n_205), .A2 (n_48), .B1 (n_56), .B2
       (n_204), .O (n_203));
  OAI22CHD g1776__2883(.A1 (n_205), .A2 (n_141), .B1 (n_149), .B2
       (n_204), .O (n_202));
  OAI22CHD g1775__2346(.A1 (n_205), .A2 (n_83), .B1 (n_59), .B2
       (n_204), .O (n_201));
  OAI22CHD g1774__1666(.A1 (n_205), .A2 (charge_time[0]), .B1 (n_55),
       .B2 (n_204), .O (n_200));
  OAI22CHD g1777__7410(.A1 (n_205), .A2 (n_137), .B1 (n_163), .B2
       (n_204), .O (n_199));
  OAI22CHD g1778__6417(.A1 (n_205), .A2 (n_170), .B1 (n_110), .B2
       (n_204), .O (n_198));
  QDFZHHD \counter_reg[4] (.CK (clk), .D (n_188), .TD (counter[3]),
       .SEL (se), .Q (counter[4]));
  AO2222BHD g1868__5477(.A1 (n_173), .A2 (n_144), .B1 (n_61), .B2
       (n_41), .C1 (n_31), .C2 (vbat[7]), .D1 (n_143), .D2 (n_129), .O
       (n_197));
  AO2222BHD g1876__2398(.A1 (n_174), .A2 (n_148), .B1 (n_60), .B2
       (n_35), .C1 (n_30), .C2 (vbat[7]), .D1 (n_147), .D2 (n_130), .O
       (n_210));
  OAI13BHD g1767__5107(.A1 (n_98), .B1 (n_186), .B2 (n_195), .B3
       (n_193), .O (n_196));
  OAI13BHD g1766__6260(.A1 (n_97), .B1 (n_179), .B2 (n_195), .B3
       (n_193), .O (n_194));
  AN4B1BHD g1860__4319(.I1 (n_181), .I2 (n_113), .I3 (n_20), .B1
       (n_159), .O (n_192));
  ND3CHD g1791__8428(.I1 (n_204), .I2 (n_187), .I3 (rstz), .O (n_205));
  AO2222BHD g1806__5526(.A1 (n_164), .A2 (n_150), .B1 (n_38), .B2
       (n_43), .C1 (charge_time[7]), .C2 (n_7), .D1 (n_77), .D2
       (n_112), .O (n_191));
  AN4B1BHD g1863__6783(.I1 (n_180), .I2 (n_115), .I3 (n_21), .B1
       (n_161), .O (n_190));
  OAI13BHD g1760__3680(.A1 (n_99), .B1 (n_176), .B2 (n_195), .B3
       (n_193), .O (n_189));
  QDFZHHD \counter_reg[3] (.CK (clk), .D (n_171), .TD (counter[2]),
       .SEL (se), .Q (counter[3]));
  QDFZHHD \counter_reg[2] (.CK (clk), .D (n_152), .TD (counter[1]),
       .SEL (se), .Q (counter[2]));
  OAI13BHD g1771__1617(.A1 (n_101), .B1 (n_157), .B2 (n_195), .B3
       (n_193), .O (n_188));
  OAI112BHD g1798__2802(.A1 (n_187), .B1 (rstz), .C1 (n_158), .C2
       (n_122), .O (n_204));
  MAOI1CHD g1799__1705(.A1 (n_185), .A2 (counter[6]), .B1 (counter[6]),
       .B2 (n_185), .O (n_186));
  MAOI1CHD g1792__5122(.A1 (n_182), .A2 (n_183), .B1 (n_183), .B2
       (n_182), .O (n_184));
  OAI112BHD g1875__8246(.A1 (n_154), .B1 (n_95), .C1 (n_28), .C2
       (tempmin[3]), .O (n_181));
  OAI112BHD g1874__7098(.A1 (n_153), .B1 (n_74), .C1 (n_29), .C2
       (tbat[3]), .O (n_180));
  QDFZHHD \counter_reg[0] (.CK (clk), .D (n_125), .TD (charge_time[7]),
       .SEL (se), .Q (counter[0]));
  MAOI1CHD g1800__6131(.A1 (n_178), .A2 (counter[5]), .B1 (counter[5]),
       .B2 (n_178), .O (n_179));
  OAI112BHD g1817__1881(.A1 (n_142), .B1 (n_105), .C1 (n_37), .C2
       (ibat[3]), .O (n_177));
  MAOI1CHD g1802__5115(.A1 (n_175), .A2 (counter[7]), .B1 (counter[7]),
       .B2 (n_175), .O (n_176));
  OAI112BHD g1897__7482(.A1 (n_145), .B1 (n_65), .C1 (n_172), .C2
       (vcutoff[3]), .O (n_174));
  OAI112BHD g1902__4733(.A1 (n_146), .B1 (n_71), .C1 (n_172), .C2
       (vpreset[3]), .O (n_173));
  QDFZHHD \counter_reg[1] (.CK (clk), .D (n_132), .TD (counter[0]),
       .SEL (se), .Q (counter[1]));
  OAI13BHD g1765__6161(.A1 (n_102), .B1 (n_127), .B2 (n_195), .B3
       (n_193), .O (n_171));
  MAOI1CHD g1793__9315(.A1 (n_169), .A2 (charge_time[5]), .B1
       (charge_time[5]), .B2 (n_169), .O (n_170));
  MAOI1CHD g1795__9945(.A1 (n_166), .A2 (n_167), .B1 (n_167), .B2
       (n_166), .O (n_168));
  OAI112BHD g1814__2346(.A1 (n_124), .B1 (n_119), .C1 (n_163), .C2
       (tmax[3]), .O (n_164));
  OAI112BHD g1864__1666(.A1 (n_51), .B1 (n_27), .C1 (n_116), .C2
       (n_161), .O (n_162));
  OAI112BHD g1865__7410(.A1 (n_90), .B1 (n_26), .C1 (n_114), .C2
       (n_159), .O (n_160));
  OR3B1EHD g1819__6417(.I1 (n_151), .I2 (n_156), .B1 (counter[7]), .O
       (n_158));
  MAOI1CHD g1936__5477(.A1 (n_156), .A2 (counter[4]), .B1 (counter[4]),
       .B2 (n_156), .O (n_157));
  OAI112BHD g1812__2398(.A1 (n_76), .B1 (n_14), .C1 (n_81), .C2
       (n_133), .O (n_155));
  OAI112BHD g1887__5107(.A1 (n_85), .B1 (n_94), .C1 (n_93), .C2
       (tbat[2]), .O (n_154));
  OAI112BHD g1888__6260(.A1 (n_86), .B1 (n_73), .C1 (n_72), .C2
       (tempmax[2]), .O (n_153));
  OAI13BHD g1764__4319(.A1 (n_109), .B1 (n_84), .B2 (n_195), .B3
       (n_193), .O (n_152));
  OR2EHD g1811__8428(.I1 (n_151), .I2 (n_156), .O (n_175));
  OR2EHD g1810__5526(.I1 (n_46), .I2 (n_156), .O (n_185));
  NR3BHD g1809__6783(.I1 (n_167), .I2 (n_131), .I3 (n_140), .O (n_182));
  AOI112BHD g1820__3680(.A1 (n_78), .B1 (n_111), .C1 (n_149), .C2
       (tmax[4]), .O (n_150));
  OA112CHD g1899__1617(.A1 (n_147), .B1 (n_67), .C1 (n_66), .C2
       (vbat[4]), .O (n_148));
  OAI112BHD g1909__2802(.A1 (n_62), .B1 (n_70), .C1 (n_69), .C2
       (vbat[2]), .O (n_146));
  OAI112BHD g1912__1705(.A1 (n_75), .B1 (n_64), .C1 (n_63), .C2
       (vbat[2]), .O (n_145));
  OA112CHD g1898__5122(.A1 (n_143), .B1 (n_88), .C1 (n_87), .C2
       (vbat[4]), .O (n_144));
  OAI112BHD g1827__8246(.A1 (n_100), .B1 (n_104), .C1 (n_103), .C2
       (iend[2]), .O (n_142));
  MAOI1CHD g1940__7098(.A1 (n_140), .A2 (charge_time[4]), .B1
       (charge_time[4]), .B2 (n_140), .O (n_141));
  OR2B1CHD g1935__6131(.I1 (n_156), .B1 (counter[4]), .O (n_178));
  OAI12CHD g1856__1881(.A1 (n_315), .B1 (n_58), .B2 (n_195), .O
       (n_139));
  MAOI1CHD g1794__5115(.A1 (n_136), .A2 (charge_time[3]), .B1
       (charge_time[3]), .B2 (n_136), .O (n_137));
  INVCKDHD g1872(.I (n_219), .O (n_135));
  AOI112BHD g1818__7482(.A1 (n_133), .B1 (n_80), .C1 (n_79), .C2
       (ibat[4]), .O (n_134));
  OAI13BHD g1770__4733(.A1 (n_108), .B1 (n_32), .B2 (n_195), .B3
       (n_193), .O (n_132));
  NR2CHD g1803__6161(.I1 (n_131), .I2 (n_140), .O (n_166));
  OAI12CHD g1910__9315(.A1 (n_68), .B1 (n_128), .B2 (vcutoff[5]), .O
       (n_130));
  OAI12CHD g1911__9945(.A1 (n_89), .B1 (n_128), .B2 (vpreset[5]), .O
       (n_129));
  MAOI1CHD g1938__2883(.A1 (n_126), .A2 (counter[3]), .B1 (counter[3]),
       .B2 (n_126), .O (n_127));
  OAI13BHD g1763__2346(.A1 (n_106), .B1 (n_195), .B2 (counter[0]), .B3
       (n_193), .O (n_125));
  OAI112BHD g1830__1666(.A1 (n_118), .B1 (n_42), .C1 (n_57), .C2
       (n_39), .O (n_124));
  OR2EHD g1939__7410(.I1 (n_149), .I2 (n_140), .O (n_169));
  NR2BHD g1749__6417(.I1 (n_122), .I2 (n_91), .O (cc));
  OR2B1CHD g1748__5477(.I1 (n_120), .B1 (en), .O (tmonen));
  OR3B2CHD g1837__2398(.I1 (tmax[2]), .B1 (charge_time[2]), .B2
       (n_118), .O (n_119));
  AOI12CHD g1877__5107(.A1 (n_33), .B1 (n_44), .B2 (n_128), .O (n_219));
  AN2CHD g1750__6260(.I1 (n_211), .I2 (en), .O (tc));
  AOI22BHD g1886__4319(.A1 (n_18), .A2 (n_115), .B1 (n_36), .B2
       (tempmax[5]), .O (n_116));
  AOI22BHD g1884__8428(.A1 (n_19), .A2 (n_113), .B1 (n_9), .B2
       (tbat[5]), .O (n_114));
  OAI22CHD g1828__5526(.A1 (n_25), .A2 (n_111), .B1 (n_110), .B2
       (tmax[5]), .O (n_112));
  OR2B1CHD g1937__6783(.I1 (n_126), .B1 (counter[3]), .O (n_156));
  ND2CHD g1779__3680(.I1 (counter[2]), .I2 (n_107), .O (n_109));
  ND2CHD g1780__1617(.I1 (counter[1]), .I2 (n_107), .O (n_108));
  ND2CHD g1781__2802(.I1 (counter[0]), .I2 (n_107), .O (n_106));
  ND3CHD g1838__1705(.I1 (n_104), .I2 (n_103), .I3 (iend[2]), .O
       (n_105));
  ND2CHD g1782__5122(.I1 (counter[3]), .I2 (n_107), .O (n_102));
  ND2CHD g1783__8246(.I1 (counter[4]), .I2 (n_107), .O (n_101));
  MAO222CHD g1840__7098(.A1 (n_22), .B1 (n_11), .C1 (iend[1]), .O
       (n_100));
  ND2CHD g1784__6131(.I1 (counter[7]), .I2 (n_107), .O (n_99));
  ND2CHD g1785__1881(.I1 (counter[6]), .I2 (n_107), .O (n_98));
  ND2CHD g1786__5115(.I1 (counter[5]), .I2 (n_107), .O (n_97));
  OR3B2CHD g1747__7482(.I1 (n_52), .B1 (n_54), .B2 (en), .O (vmonen));
  ND3CHD g1890__4733(.I1 (n_94), .I2 (n_93), .I3 (tbat[2]), .O (n_95));
  INVDHD g1866(.I (n_91), .O (n_92));
  OR3B2CHD g1879__6161(.I1 (tempmin[6]), .B1 (n_53), .B2 (tbat[6]), .O
       (n_90));
  DFZCRBEHD \state_reg[1] (.CK (clk), .D (nxt_state[1]), .RB (en), .TD
       (n_0), .SEL (se), .Q (state[1]), .QB (n_2));
  DFZCRBEHD \state_reg[2] (.CK (clk), .D (nxt_state[2]), .RB (en), .TD
       (n_2), .SEL (se), .Q (state[2]), .QB (so));
  ND3CHD g1923__9945(.I1 (n_88), .I2 (n_87), .I3 (vbat[4]), .O (n_89));
  MAO222CHD g1896__2883(.A1 (n_24), .B1 (n_10), .C1 (tempmax[1]), .O
       (n_86));
  MAO222CHD g1901__2346(.A1 (n_15), .B1 (n_3), .C1 (tbat[1]), .O
       (n_85));
  XNR2CHD g1944__1666(.I1 (counter[2]), .I2 (n_45), .O (n_84));
  MAOI1CHD g1943__7410(.A1 (n_82), .A2 (charge_time[2]), .B1
       (charge_time[2]), .B2 (n_82), .O (n_83));
  OA13CHD g1829__6417(.A1 (n_23), .B1 (n_80), .B2 (n_79), .B3
       (ibat[4]), .O (n_81));
  INVDHD g1821(.I (n_77), .O (n_78));
  OR3B2CHD g1823__5477(.I1 (ibat[6]), .B1 (n_47), .B2 (iend[6]), .O
       (n_76));
  MAO222CHD g1922__2398(.A1 (n_13), .B1 (n_4), .C1 (vbat[1]), .O
       (n_75));
  ND3CHD g1893__5107(.I1 (n_73), .I2 (n_72), .I3 (tempmax[2]), .O
       (n_74));
  ND3CHD g1924__6260(.I1 (n_70), .I2 (n_69), .I3 (vbat[2]), .O (n_71));
  ND3CHD g1925__4319(.I1 (n_67), .I2 (n_66), .I3 (vbat[4]), .O (n_68));
  ND3CHD g1926__8428(.I1 (n_64), .I2 (n_63), .I3 (vbat[2]), .O (n_65));
  MAO222CHD g1927__5526(.A1 (n_12), .B1 (n_6), .C1 (vbat[1]), .O
       (n_62));
  AN2CHD g1913__6783(.I1 (n_61), .I2 (n_17), .O (n_143));
  AN2CHD g1914__3680(.I1 (n_60), .I2 (n_16), .O (n_147));
  DFZCRBEHD \state_reg[0] (.CK (clk), .D (nxt_state[0]), .RB (en), .TD
       (nxt_state[2]), .SEL (se), .Q (state[0]), .QB (n_0));
  OR3EHD g1945__1617(.I1 (n_163), .I2 (n_59), .I3 (n_82), .O (n_140));
  NR8EHD g1873__2802(.I1 (charge_time[3]), .I2 (charge_time[6]), .I3
       (charge_time[1]), .I4 (charge_time[4]), .I5 (charge_time[5]),
       .I6 (charge_time[2]), .I7 (charge_time[7]), .I8
       (charge_time[0]), .O (n_58));
  AOI22BHD g1850__1705(.A1 (n_56), .A2 (tmax[1]), .B1 (n_55), .B2
       (tmax[0]), .O (n_57));
  OAI12CHD g1881__5122(.A1 (n_50), .B1 (n_49), .B2 (tempmax[6]), .O
       (n_161));
  NR2BHD g1752__8246(.I1 (n_122), .I2 (n_195), .O (cv));
  OR2B1CHD g1869__7098(.I1 (n_54), .B1 (state[1]), .O (n_91));
  OAI12CHD g1882__6131(.A1 (n_53), .B1 (n_5), .B2 (tbat[6]), .O
       (n_159));
  AN2B1CHD g1857__1881(.I1 (n_52), .B1 (state[2]), .O (n_214));
  NR2CHD g1870__5115(.I1 (state[1]), .I2 (n_54), .O (n_211));
  ND3CHD g1885__7482(.I1 (n_50), .I2 (n_49), .I3 (tempmax[6]), .O
       (n_51));
  AOI22BHD g1949__4733(.A1 (n_56), .A2 (charge_time[0]), .B1 (n_55),
       .B2 (charge_time[1]), .O (n_48));
  OAI12CHD g1824__6161(.A1 (n_47), .B1 (n_8), .B2 (iend[6]), .O
       (n_133));
  AOI22BHD g1825__9315(.A1 (n_183), .A2 (tmax[7]), .B1 (n_167), .B2
       (tmax[6]), .O (n_77));
  ND2CHD g1826__9945(.I1 (n_195), .I2 (state[2]), .O (n_120));
  OR2EHD g1941__2883(.I1 (n_59), .I2 (n_82), .O (n_136));
  OR2B1CHD g1833__2346(.I1 (n_46), .B1 (counter[6]), .O (n_151));
  ND2CHD g1813__1666(.I1 (n_195), .I2 (en), .O (n_187));
  ND2DHD g1942__7410(.I1 (n_45), .I2 (counter[2]), .O (n_126));
  OAI22CHD g1900__6417(.A1 (vbat[1]), .A2 (vbat[3]), .B1 (vbat[3]), .B2
       (vbat[2]), .O (n_44));
  NR2CHD g1839__5477(.I1 (tmax[6]), .I2 (n_167), .O (n_43));
  ND2CHD g1842__2398(.I1 (n_59), .I2 (tmax[2]), .O (n_42));
  NR2BHD g1928__5107(.I1 (vpreset[6]), .I2 (n_34), .O (n_41));
  NR2CHD g1849__6260(.I1 (tmax[1]), .I2 (n_56), .O (n_39));
  ND2CHD g1835__4319(.I1 (n_183), .I2 (tmax[7]), .O (n_38));
  ND2CHD g1845__8428(.I1 (n_37), .I2 (ibat[3]), .O (n_104));
  ND2CHD g1846__5526(.I1 (n_163), .I2 (tmax[3]), .O (n_118));
  AN2EHD g1844__6783(.I1 (n_110), .I2 (tmax[5]), .O (n_111));
  OR2CHD g1905__3680(.I1 (tempmax[5]), .I2 (n_36), .O (n_115));
  AN2CHD g1789__1617(.I1 (n_122), .I2 (rstz), .O (n_107));
  NR2BHD g1915__2802(.I1 (vcutoff[6]), .I2 (n_34), .O (n_35));
  OAI112BHD g1889__1705(.A1 (vbat[7]), .B1 (vbat[6]), .C1 (vbat[5]),
       .C2 (vbat[4]), .O (n_33));
  XNR2EHD g1948__5122(.I1 (counter[0]), .I2 (counter[1]), .O (n_32));
  ND2CHD g1929__8246(.I1 (n_128), .I2 (vpreset[5]), .O (n_88));
  OR2CHD g1920__7098(.I1 (vbat[7]), .I2 (n_31), .O (n_61));
  OR2CHD g1921__6131(.I1 (vbat[7]), .I2 (n_30), .O (n_60));
  ND2CHD g1906__1881(.I1 (n_29), .I2 (tbat[3]), .O (n_73));
  ND2CHD g1930__5115(.I1 (n_172), .I2 (vcutoff[3]), .O (n_64));
  ND2CHD g1931__7482(.I1 (n_128), .I2 (vcutoff[5]), .O (n_67));
  ND2CHD g1932__4733(.I1 (n_172), .I2 (vpreset[3]), .O (n_70));
  ND2CHD g1907__6161(.I1 (n_36), .I2 (tempmin[5]), .O (n_113));
  ND2CHD g1908__9315(.I1 (n_28), .I2 (tempmin[3]), .O (n_94));
  OR2B1CHD g1880__9945(.I1 (tbat[7]), .B1 (tempmax[7]), .O (n_27));
  OR2B1CHD g1878__2883(.I1 (tempmin[7]), .B1 (tbat[7]), .O (n_26));
  OR2B1CHD g1848__2346(.I1 (tmax[4]), .B1 (charge_time[4]), .O (n_25));
  OR2B1CHD g1916__1666(.I1 (tempmax[0]), .B1 (tbat[0]), .O (n_24));
  OR2B1CHD g1832__7410(.I1 (ibat[5]), .B1 (iend[5]), .O (n_23));
  OR2B1CHD g1853__6417(.I1 (iend[0]), .B1 (ibat[0]), .O (n_22));
  AN2B1CHD g1843__5477(.I1 (ibat[5]), .B1 (iend[5]), .O (n_80));
  NR2CHD g1861__2398(.I1 (state[1]), .I2 (state[0]), .O (n_52));
  OR2B1CHD g1834__5107(.I1 (iend[7]), .B1 (ibat[7]), .O (n_47));
  ND2CHD g1851__6260(.I1 (counter[4]), .I2 (counter[5]), .O (n_46));
  ND2CHD g1947__4319(.I1 (charge_time[0]), .I2 (charge_time[1]), .O
       (n_82));
  ND2CHD g1790__8428(.I1 (en), .I2 (rstz), .O (n_193));
  OR2B1CHD g1871__5526(.I1 (state[0]), .B1 (state[1]), .O (n_195));
  OR2B1CHD g1891__6783(.I1 (tempmax[4]), .B1 (tbat[4]), .O (n_21));
  OR2B1CHD g1892__3680(.I1 (tbat[4]), .B1 (tempmin[4]), .O (n_20));
  AN2B1CHD g1903__1617(.I1 (tbat[4]), .B1 (tempmin[4]), .O (n_19));
  AN2B1CHD g1904__2802(.I1 (tempmax[4]), .B1 (tbat[4]), .O (n_18));
  OR2B1CHD g1917__1705(.I1 (vbat[6]), .B1 (vpreset[6]), .O (n_17));
  OR2B1CHD g1918__5122(.I1 (vbat[6]), .B1 (vcutoff[6]), .O (n_16));
  OR2B1CHD g1919__8246(.I1 (tbat[0]), .B1 (tempmin[0]), .O (n_15));
  OR2B1CHD g1822__7098(.I1 (ibat[7]), .B1 (iend[7]), .O (n_14));
  OR2B1CHD g1933__6131(.I1 (vbat[0]), .B1 (vcutoff[0]), .O (n_13));
  OR2B1CHD g1934__1881(.I1 (vbat[0]), .B1 (vpreset[0]), .O (n_12));
  OR2B1CHD g1894__5115(.I1 (tempmax[7]), .B1 (tbat[7]), .O (n_50));
  AN2EHD g1946__7482(.I1 (counter[1]), .I2 (counter[0]), .O (n_45));
  OR2B1CHD g1895__4733(.I1 (tbat[7]), .B1 (tempmin[7]), .O (n_53));
  ND2CHD g1816__6161(.I1 (charge_time[4]), .I2 (charge_time[5]), .O
       (n_131));
  OR2B1CHD g1883__9315(.I1 (state[2]), .B1 (state[0]), .O (n_54));
  INVCKDHD g1951(.I (ibat[1]), .O (n_11));
  INVCKDHD g1979(.I (tbat[1]), .O (n_10));
  INVCKDHD g1975(.I (tempmin[5]), .O (n_9));
  INVCKDHD g1973(.I (ibat[6]), .O (n_8));
  INVCKDHD g1972(.I (tmax[7]), .O (n_7));
  INVCKDHD g1970(.I (vpreset[1]), .O (n_6));
  INVCKDHD g1954(.I (ibat[2]), .O (n_103));
  INVCKDHD g1974(.I (vpreset[7]), .O (n_31));
  INVCKDHD g1955(.I (vpreset[2]), .O (n_69));
  INVCKDHD g1960(.I (tbat[3]), .O (n_28));
  INVCKDHD g1952(.I (tempmax[3]), .O (n_29));
  INVCKDHD g1959(.I (tbat[2]), .O (n_72));
  INVCKDHD g1978(.I (tbat[5]), .O (n_36));
  INVCKDHD g1981(.I (vbat[3]), .O (n_172));
  INVCKDHD g1967(.I (en), .O (n_122));
  INVDHD g1966(.I (charge_time[2]), .O (n_59));
  INVCKDHD g1982(.I (vbat[5]), .O (n_128));
  INVDHD g1965(.I (charge_time[6]), .O (n_167));
  INVCKDHD g1958(.I (tempmin[6]), .O (n_5));
  INVCKDHD g1957(.I (vcutoff[1]), .O (n_4));
  INVCKDHD g1953(.I (tempmin[1]), .O (n_3));
  INVCKDHD g1968(.I (tempmin[2]), .O (n_93));
  INVCKDHD g1969(.I (vcutoff[4]), .O (n_66));
  INVCKDHD g1971(.I (vpreset[4]), .O (n_87));
  INVCKDHD g1977(.I (vcutoff[7]), .O (n_30));
  INVCKDHD g1950(.I (vcutoff[2]), .O (n_63));
  INVCKDHD g1976(.I (iend[3]), .O (n_37));
  INVCKDHD g1980(.I (vbat[6]), .O (n_34));
  INVCKDHD g1961(.I (tbat[6]), .O (n_49));
  INVCKDHD g1956(.I (iend[4]), .O (n_79));
  INVDHD g1983(.I (charge_time[5]), .O (n_110));
  INVDHD g1985(.I (charge_time[4]), .O (n_149));
  INVDHD g1984(.I (charge_time[0]), .O (n_55));
  INVDHD g1964(.I (charge_time[3]), .O (n_163));
  INVDHD g1963(.I (charge_time[1]), .O (n_56));
  INVDHD g1962(.I (charge_time[7]), .O (n_183));
  AN4B1BHD g2(.I1 (n_224), .I2 (n_221), .I3 (n_120), .B1 (n_230), .O
       (n_313));
  OAI12CHD g2008(.A1 (state[2]), .B1 (n_135), .B2 (state[0]), .O
       (n_314));
  OR2B1CHD g2009(.I1 (n_195), .B1 (state[2]), .O (n_315));
endmodule

